export interface GeneralInformationResponseData{
    status:number,
    data:GeneralInformationModel
}

export interface GeneralInformationModel
{
    id: string,
    name: string,
    surname: string,
    class: number,
    register_year:number,
    register_date:string,
    lisansUstuSinif:string,
    uyruk: string,
    mezuniyet_ayrilma_tarihi: string,
    yatay_gecis_kayit_tarihi: string,
    yatay_gecis_birim_id: number,
    kayit_tipi: string,
    cap_durumu?:string,
    yandal_durumu?: string,
    cap_durum_tarihi?: string,
    yandal_durum_tarihi?: string,
    ikinci_yabanci_dil?: string,
    mut_tercumanlik_dili?: string,
    disiplin_cezasi?: string,
    tc_kimlik_no: string,
    danisman: string,
    cap_danisman?: string,
    yandal_danisman?: string,
    ogr_hakkini_kaybettigi_tarih?: string,
    gno_hesabi: string,
    tabi_oldugu_plan: string,
    lisans_ustu_ucret: string,
    ayni_programi_tekrar_okuma:string,
    tabi_olunan_musredat: string,
    ilave_burs?: string,
    anadal_fakulte: string,
    anadal_bolum: string,
    anadal_opsiyon?: string,
    email: string,
    telefon: string,
    cap_fakulte?: string,
    cap_bolum?: string,
    cap_opsiyon?: string,
    yandal_fakulte?: string,
    yandal_bolum?: string,
    yandal_opsiyon?: string,
    std_state: string,
    state_date: string,
    burs_durumu: string,
    burs_tipi: string,
    alinan_ders: number,
}